name: actions with IAM role
'on':
  - push

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  IAM_ROLE: ${{secrets.IAM_ROLE}}

permissions:
  contents: read
  id-token: write

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: tarball it
        run: |
          mkdir -p /tmp/reactoscope
          cp -r . /tmp/reactoscope
          tar -czvf reactoscope.tar.gz -C /tmp/reactoscope .

      - name: config AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.IAM_ROLE}}
          role-session-name: github-actions-federation
          aws-region: ${{env.AWS_REGION}}

      - name: upload to S3
        run: aws s3 cp reactoscope.tar.gz s3://mr-bucket-balls-pop-out-of-my-mouth/
