name: actions with IAM role
'on':
  - push

env:
  AWS_REGION: ${{secrets.AWS_REGION}}
  IAM_ROLE: ${{secrets.IAM_ROLE}}
  INSTANCE_TYPE: t2.micro
  IMAGE_RECIPE_ARN: arn:aws:imagebuilder:us-east-2:744657158806:image-recipe/reactoscope-ami/0.0.1
  KEY_NAME: reactoscope
  SECURITY_GROUP: sg-0802300961999d6ec
  SUBNET_ID: subnet-4ed42225
  INSTANCE_PROFILE: EC2InstanceProfileForImageBuilder

permissions:
  contents: read
  id-token: write

jobs:
  AssumeRole:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: tarball it
        run: |
          mkdir -p /tmp/reactoscope
          cp -r . /tmp/reactoscope
          tar -czvf reactoscope.tar.gz -C /tmp/reactoscope .

      - name: config AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.IAM_ROLE}}
          role-session-name: github-actions-federation
          aws-region: ${{env.AWS_REGION}}

      - name: upload to S3
        run: aws s3 cp reactoscope.tar.gz s3://reactoscope-ami/
